version: "1"

services:
  ui:
    build: "./client"
    ports:
      - "3001:80"
    depends_on:
      - server
  api:
    build: "./server"
    ports:
      - "8080:8080"
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - "27017:27017"
