POST http://localhost:5000/api/users/register

content-type: application/x-www-form-urlencoded

{
    "name": "Phani Kumar",
    "email": "test@test.com",
    "password": "test123",
    "password2": "test123",
    "role": "Guest",
    "status": "Active",
}

###

POST https://developers.myoperator.co/search?token=955ea4604e2f58e4b693192251f3b5ef

{"content-type": "application/x-www-form-urlencoded"}